# Generated by Django 4.1 on 2022-10-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_ledger_vouchers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ledger_vouchers',
            new_name='Ledger_vouchers_new',
        ),
    ]
