# Generated by Django 4.1 on 2022-10-05 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_ledger_vouchers_ledger_vouchers_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger_vouchers_new',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tally_group'),
        ),
    ]
