# Generated by Django 4.1 on 2022-10-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_ledger_voucher_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger_vouchers_new',
            name='closing_balance',
            field=models.IntegerField(null=True),
        ),
    ]
