# Generated by Django 4.1 on 2022-10-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_ledger_vouchers_new_closing_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_vouchers_new',
            name='closing_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
