# Generated by Django 4.1 on 2022-10-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_ledger_vouchers_new_closing_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger_vouchers_new',
            name='closing_balance',
        ),
        migrations.AddField(
            model_name='ledger_vouchers_new',
            name='month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
