# Generated by Django 4.1 on 2022-10-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger_vouchers_new',
            name='month',
        ),
    ]
