# Generated by Django 4.1 on 2022-10-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_ledger_vouchers_new_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='month',
        ),
    ]
