# Generated by Django 4.1 on 2022-10-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_delete_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger_vouchers_new',
            name='closing_balance',
            field=models.IntegerField(null=True),
        ),
    ]
