# Generated by Django 4.1 on 2022-10-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_ledger_vouchers_new_closing_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger_vouchers_new',
            name='cb',
            field=models.IntegerField(null=True),
        ),
    ]
