# Generated by Django 4.1 on 2022-10-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_cb_ledger_vouchers_new_cbalance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger_vouchers_new',
            old_name='cbalance',
            new_name='c_balance',
        ),
    ]
