# Generated by Django 4.1 on 2022-10-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_voucher_type_creation_model_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher_type_creation_model',
            name='new',
        ),
    ]
