# Generated by Django 4.1 on 2022-10-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_tally_ledger_c_blnc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tally_ledger',
            name='c_blnc_type',
        ),
    ]
