# Generated by Django 4.1 on 2022-10-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_rename_c_balance_tally_ledger_c_balance_cred_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tally_ledger',
            old_name='c_balance_cred',
            new_name='c_balance',
        ),
        migrations.RemoveField(
            model_name='tally_ledger',
            name='c_balance_deb',
        ),
    ]
