# Generated by Django 4.1 on 2022-10-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rename_c_balance_cred_tally_ledger_c_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally_ledger',
            name='c_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
