# Generated by Django 4.1 on 2022-10-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_total_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_balance',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='total_balance',
            name='voucher',
        ),
        migrations.AddField(
            model_name='total_balance',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
