# Generated by Django 4.1 on 2022-10-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_total_balance_c_balance_total_balance_c_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_balance',
            name='c_balance',
        ),
        migrations.RemoveField(
            model_name='total_balance',
            name='c_type',
        ),
    ]
