# Generated by Django 4.1 on 2022-10-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_total_balance_c_balance_total_balance_c_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_balance',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tally_ledger'),
        ),
    ]
