# Generated by Django 4.1 on 2022-10-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_total_balance_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_balance',
            name='c_balance',
        ),
        migrations.RemoveField(
            model_name='total_balance',
            name='c_type',
        ),
        migrations.RemoveField(
            model_name='total_balance',
            name='ledger',
        ),
    ]
